const products = [
  {
    _id: '1',
    name: 'Wireless Bluetooth Headphones',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=80',
    price: 120,
    countInStock: 10,
    brand: 'Sony',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
  },
  {
    _id: '2',
    name: 'Apple iPhone 15 Pro',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=500&q=80',
    price: 999,
    countInStock: 20,
    brand: 'Apple',
    rating: 4.9,
    numReviews: 50,
    description: 'Latest and greatest iPhone with pro camera system',
  },
  {
    _id: '3',
    name: 'Men Slim Fit Casual Shirt',
    category: 'Shirts',
    image: 'https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: 35,
    countInStock: 15,
    brand: 'Nike',
    rating: 4.2,
    numReviews: 14,
    description: 'high quality product',
  },
  {
    _id: '4',
    name: 'Ergonomic Office Chair',
    category: 'Furniture',
    image: 'https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?w=500&q=80',
    price: 150,
    countInStock: 5,
    brand: 'Herman Miller',
    rating: 4.8,
    numReviews: 32,
    description: 'Highly comfortable chair for long working hours',
  },
  {
    _id: '5',
    name: 'Classic Running Shoes',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&q=80',
    price: 85,
    countInStock: 30,
    brand: 'Puma',
    rating: 4.5,
    numReviews: 10,
    description: 'high quality product',
  },
  {
    _id: '6',
    name: 'Smart Watch Series 7',
    category: 'Electronics',
    image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=500&q=80',
    price: 399,
    countInStock: 12,
    brand: 'Apple',
    rating: 4.7,
    numReviews: 24,
    description: 'Track your fitness, stay connected with the world',
  },
  {
    _id: '7',
    name: 'Sony PlayStation 5 Console',
    category: 'Electronics',
    image: 'https://images.pexels.com/photos/1018911/pexels-photo-1018911.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: 499,
    countInStock: 8,
    brand: 'Sony',
    rating: 4.9,
    numReviews: 120,
    description: 'Experience lightning-fast loading with an ultra-high speed SSD.',
  },
  {
    _id: '8',
    name: 'Logitech G Pro Wireless Mouse',
    category: 'Electronics',
    image: 'https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: 129,
    countInStock: 25,
    brand: 'Logitech',
    rating: 4.8,
    numReviews: 85,
    description: 'Designed to be the ultimate gaming mouse for esports professionals.',
  },
];

module.exports = products;
